# Shotspotter districts
shotspotter_districts:
  - 7
  - 11
  - 15
  - 9
  - 6
  - 10
  - 3
  - 4
  - 5
  - 25
  - 8
  - 2

south_srdd_study_districts:
  - 22
  - 5
  - 6
  - 8

north_srdd_study_districts:
  - 1
  - 2
  - 9
  - 10
  - 11
  - 12
  - 14
  - 16
  - 17
  - 25

first_shotspotter_implementation_date: "2017-01-13"
last_shotspotter_implementation_date: "2018-05-16"

# Time params
min_shooting_year: 2010
max_shooting_year: 2024

# Location of occurence
location_logic: "outdoor_shooting == 1 | indoor_outdoor_shooting == 1"

outdoor_locations:
  - "AIRPORT EXTERIOR - NON-SECURE AREA"
  - "AIRPORT EXTERIOR - SECURE AREA"
  - "ALLEY"
  - "BEACH"
  - "BRIDGE"
  - "CATCH BASIN"
  - "CEMETARY"
  - "CHA GROUNDS"
  - "CHA PLAY LOT"
  - "CONSTRUCTION SITE"
  - "DRIVEWAY"
  - "DRIVEWAY - RESIDENTIAL"
  - "DUMPSTER"
  - "EXPRESSWAY EMBANKMENT"
  - "FIRE ESCAPE"
  - "FOREST PRESERVE"
  - "GANGWAY"
  - "GAS STATION DRIVE/PROP."
  - "HIGHWAY / EXPRESSWAY"
  - "HIGHWAY/EXPRESSWAY"
  - "JUNK YARD/GARBAGE DUMP"
  - "LAGOON"
  - "LAKE"
  - "LAKEFRONT / WATERFRONT / RIVERBANK"
  - "LAKEFRONT/WATERFRONT/RIVERBANK"
  - "LOADING DOCK"
  - "PRAIRIE"
  - "RIVER"
  - "RIVER BANK"
  - "SCHOOL YARD"
  - "SEWER"
  - "SIDEWALK"
  - "STREET"
  - "VACANT LOT"
  - "VACANT LOT / LAND"
  - "VACANT LOT/LAND"
  - "WOODED AREA"
  - "YARD"

indoor_outdoor_locations:
  - "(NOT PROVIDED)"
  - "AIRCRAFT"
  - "AIRPORT PARKING LOT"
  - "AIRPORT TRANSPORTATION SYSTEM (ATS)"
  - "AIRPORT/AIRCRAFT"
  - "ATM (AUTOMATIC TELLER MACHINE)"
  - "AUTO"
  - "AUTO / BOAT / RV DEALERSHIP"
  - "BOAT / WATERCRAFT"
  - "BOAT/WATERCRAFT"
  - "CHA PARKING LOT"
  - "CHA PARKING LOT / GROUNDS"
  - "CHA PARKING LOT/GROUNDS"
  - "CHURCH PROPERTY"
  - "COIN OPERATED MACHINE"
  - "COLLEGE / UNIVERSITY - GROUNDS"
  - "COLLEGE/UNIVERSITY GROUNDS"
  - 'CTA "L" PLATFORM'
  - "CTA BUS"
  - "CTA BUS STOP"
  - "CTA GARAGE / OTHER PROPERTY"
  - "CTA L PLATFORM"
  - 'CTA "L" TRAIN'
  - "CTA PARKING LOT / GARAGE / OTHER PROPERTY"
  - "CTA PLATFORM"
  - "CTA PROPERTY"
  - "CTA STATION"
  - "CTA SUBWAY STATION"
  - "CTA TRACKS - RIGHT OF WAY"
  - "CTA TRAIN"
  - "DELIVERY TRUCK"
  - "FARM"
  - "GAS STATION"
  - "GOVERNMENT BUILDING / PROPERTY"
  - "GOVERNMENT BUILDING/PROPERTY"
  - "HORSE STABLE"
  - "HOSPITAL BUILDING / GROUNDS"
  - "HOSPITAL BUILDING/GROUNDS"
  - "LIVERY AUTO"
  - "MISSING"
  - "NA"
  - "NEWSSTAND"
  - "OTHER"
  - "OTHER (SPECIFY)"
  - "OTHER COMMERCIAL TRANSPORTATION"
  - "OTHER RAILROAD PROP / TRAIN DEPOT"
  - "OTHER RAILROAD PROPERTY / TRAIN DEPOT"
  - "PARK PROPERTY"
  - "PARKING LOT"
  - "PARKING LOT / GARAGE (NON RESIDENTIAL)"
  - "PARKING LOT/GARAGE(NON.RESID.)"
  - "POLICE FACILITY / VEHICLE PARKING LOT"
  - "POLICE FACILITY/VEH PARKING LOT"
  - "PORCH"
  - "RAILROAD PROPERTY"
  - "RAILROAD TRAIN"
  - "RELIEF SHELTER"
  - "RESIDENCE - YARD (FRONT / BACK)"
  - "RESIDENTIAL YARD (FRONT/BACK)"
  - "SCHOOL - PRIVATE GROUNDS"
  - "SCHOOL - PUBLIC GROUNDS"
  - "SCHOOL, PRIVATE, GROUNDS"
  - "SCHOOL, PUBLIC, GROUNDS"
  - "SPORTS ARENA / STADIUM"
  - "SPORTS ARENA/STADIUM"
  - "TAXI CAB"
  - "TAXICAB"
  - "TRAILER"
  - "TRUCK"
  - "TRUCKING TERMINAL"
  - "VEHICLE - COMMERCIAL"
  - "VEHICLE - COMMERCIAL: ENTERTAINMENT / PARTY BUS"
  - "VEHICLE - COMMERCIAL: TROLLEY BUS"
  - "VEHICLE - DELIVERY TRUCK"
  - "VEHICLE - OTHER RIDE SERVICE"
  - "VEHICLE - OTHER RIDE SHARE SERVICE (E.G., UBER, LYFT)"
  - "VEHICLE - OTHER RIDE SHARE SERVICE (LYFT, UBER, ETC.)"
  - "VEHICLE NON-COMMERCIAL"
  - "VEHICLE-COMMERCIAL"
  - "VEHICLE-COMMERCIAL - ENTERTAINMENT/PARTY BUS"
  - "VEHICLE-COMMERCIAL - TROLLEY BUS"
  - "YMCA"
